package recon

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"sort"
)

// Plan is the deterministic, operator-confirmable align plan computed when a Report is
// MISMATCH. ID is stable across calls with identical Steps + the ABSOLUTE snapshot
// receipt stamps (PosAtMs/OrdAtMs), so a confirm request naming an ID can be safely
// rejected by the wiring layer (Task 7/8) if the underlying picture changed underneath
// it. Deliberately NOT hashed against PosAgeMs/OrdAgeMs: those are recomputed against
// the live clock on every read (accounts.Store.Snapshot), so hashing them made the id
// shown at page-poll time never match the id recomputed at button-click time even a
// second later — every confirm 409'd. The stamps only change when the table itself
// actually changes.
type Plan struct {
	ID    string
	Steps []Step
}

// Step is one corrective action in an align Plan.
//   - "cancel_order": an ORPHAN active QUIK order (OrderNum, Symbol set).
//   - "close_position": NOT GENERATED by this package (an "excess account
//     position" is contextual — it can include the operator's own manual
//     trading, not just robot activity — so it is reported for context only,
//     never planned as a corrective action). The Kind string and Step fields
//     it would have used (Symbol, signed Qty) are kept here only so a
//     historical/legacy plan value still decodes; internal/status's Aligner
//     hard-refuses this Kind rather than acting on it.
//   - "fix_state": a robot's belief about a working order that QUIK does not have
//     (RobotID, OrderNum, Symbol set; SetPos/SetAvg carry the robot's CURRENT
//     position/avg to reset to once its phantom working order is cleared).
type Step struct {
	Kind     string
	Detail   string
	Symbol   string
	OrderNum string
	Qty      int64
	RobotID  string
	SetPos   int64
	SetAvg   float64
}

// sortSteps orders steps by (Kind, Symbol, OrderNum, RobotID) so that Report/Plan
// output never depends on the order in which the caller's Inputs slices (or any map
// iterated while building them) were arranged.
func sortSteps(steps []Step) {
	sort.SliceStable(steps, func(i, j int) bool {
		if steps[i].Kind != steps[j].Kind {
			return steps[i].Kind < steps[j].Kind
		}
		if steps[i].Symbol != steps[j].Symbol {
			return steps[i].Symbol < steps[j].Symbol
		}
		if steps[i].OrderNum != steps[j].OrderNum {
			return steps[i].OrderNum < steps[j].OrderNum
		}
		return steps[i].RobotID < steps[j].RobotID
	})
}

// planID hashes the canonical JSON of the (already-sorted) steps plus the ABSOLUTE
// snapshot receipt stamps that gated the evaluation, and returns the first 12 hex chars
// of the sha256 digest. No time.Now/rand: identical Steps + stamps always yield the
// same ID, and any change to either changes it — but re-reading the SAME underlying
// tables a moment later (ages ticking up, stamps unchanged) yields the identical ID.
func planID(steps []Step, posAtMs, ordAtMs int64) string {
	payload := struct {
		Steps   []Step
		PosAtMs int64
		OrdAtMs int64
	}{Steps: steps, PosAtMs: posAtMs, OrdAtMs: ordAtMs}
	data, err := json.Marshal(payload)
	if err != nil {
		// payload contains only strings/ints/floats/slices of structs thereof — it
		// cannot fail to marshal. Kept as a defensive fallback, not a live path.
		data = []byte(err.Error())
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])[:12]
}
