# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shectory.quik.v1 import quik_agent_pb2 as shectory_dot_quik_dot_v1_dot_quik__agent__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in shectory/quik/v1/quik_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuikAgentLinkStub(object):
    """---- Session: single bidi stream, agent -> STL = AgentMessage, STL -> agent = OrchestratorMessage.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/shectory.quik.v1.QuikAgentLink/Session',
                request_serializer=shectory_dot_quik_dot_v1_dot_quik__agent__pb2.AgentMessage.SerializeToString,
                response_deserializer=shectory_dot_quik_dot_v1_dot_quik__agent__pb2.OrchestratorMessage.FromString,
                _registered_method=True)


class QuikAgentLinkServicer(object):
    """---- Session: single bidi stream, agent -> STL = AgentMessage, STL -> agent = OrchestratorMessage.
    """

    def Session(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuikAgentLinkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=shectory_dot_quik_dot_v1_dot_quik__agent__pb2.AgentMessage.FromString,
                    response_serializer=shectory_dot_quik_dot_v1_dot_quik__agent__pb2.OrchestratorMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shectory.quik.v1.QuikAgentLink', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shectory.quik.v1.QuikAgentLink', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuikAgentLink(object):
    """---- Session: single bidi stream, agent -> STL = AgentMessage, STL -> agent = OrchestratorMessage.
    """

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/shectory.quik.v1.QuikAgentLink/Session',
            shectory_dot_quik_dot_v1_dot_quik__agent__pb2.AgentMessage.SerializeToString,
            shectory_dot_quik_dot_v1_dot_quik__agent__pb2.OrchestratorMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
