# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shectory/quik/v1/runner_bridge.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'shectory/quik/v1/runner_bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shectory.quik.v1 import quik_agent_pb2 as shectory_dot_quik_dot_v1_dot_quik__agent__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$shectory/quik/v1/runner_bridge.proto\x12\x10shectory.quik.v1\x1a!shectory/quik/v1/quik_agent.proto\"\x1b\n\nTickFilter\x12\r\n\x05\x63odes\x18\x01 \x03(\t\"%\n\x0c\x45ventsFilter\x12\x15\n\rclient_prefix\x18\x01 \x01(\t\"3\n\x0c\x43ontrolHello\x12\x16\n\x0erunner_version\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\x05\"\xc4\x02\n\rRunnerControl\x12/\n\x06\x64\x65ploy\x18\x01 \x01(\x0b\x32\x1d.shectory.quik.v1.DeployRobotH\x00\x12\x33\n\x08undeploy\x18\x02 \x01(\x0b\x32\x1f.shectory.quik.v1.UndeployRobotH\x00\x12\x36\n\nset_params\x18\x03 \x01(\x0b\x32 .shectory.quik.v1.SetRobotParamsH\x00\x12-\n\x05pause\x18\x04 \x01(\x0b\x32\x1c.shectory.quik.v1.PauseRobotH\x00\x12-\n\x05start\x18\x05 \x01(\x0b\x32\x1c.shectory.quik.v1.StartRobotH\x00\x12,\n\x04kill\x18\x06 \x01(\x0b\x32\x1c.shectory.quik.v1.KillSwitchH\x00\x42\t\n\x07payload\"&\n\tBridgeAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xfb\x03\n\x0cRunnerBridge\x12O\n\x0bStreamTicks\x12\x1c.shectory.quik.v1.TickFilter\x1a .shectory.quik.v1.MarketDataTick0\x01\x12M\n\x10PlaceRunnerOrder\x12\x1c.shectory.quik.v1.PlaceOrder\x1a\x1b.shectory.quik.v1.BridgeAck\x12O\n\x11\x43\x61ncelRunnerOrder\x12\x1d.shectory.quik.v1.CancelOrder\x1a\x1b.shectory.quik.v1.BridgeAck\x12T\n\x11StreamOrderEvents\x12\x1e.shectory.quik.v1.EventsFilter\x1a\x1d.shectory.quik.v1.OrderUpdate0\x01\x12R\n\rStreamControl\x12\x1e.shectory.quik.v1.ControlHello\x1a\x1f.shectory.quik.v1.RunnerControl0\x01\x12P\n\x0cReportStatus\x12#.shectory.quik.v1.RobotStatusReport\x1a\x1b.shectory.quik.v1.BridgeAckB\x19Z\x17shectory/quik/v1;quikv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shectory.quik.v1.runner_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027shectory/quik/v1;quikv1'
  _globals['_TICKFILTER']._serialized_start=93
  _globals['_TICKFILTER']._serialized_end=120
  _globals['_EVENTSFILTER']._serialized_start=122
  _globals['_EVENTSFILTER']._serialized_end=159
  _globals['_CONTROLHELLO']._serialized_start=161
  _globals['_CONTROLHELLO']._serialized_end=212
  _globals['_RUNNERCONTROL']._serialized_start=215
  _globals['_RUNNERCONTROL']._serialized_end=539
  _globals['_BRIDGEACK']._serialized_start=541
  _globals['_BRIDGEACK']._serialized_end=579
  _globals['_RUNNERBRIDGE']._serialized_start=582
  _globals['_RUNNERBRIDGE']._serialized_end=1089
# @@protoc_insertion_point(module_scope)
