# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shectory.quik.v1 import quik_agent_pb2 as shectory_dot_quik_dot_v1_dot_quik__agent__pb2
from shectory.quik.v1 import runner_bridge_pb2 as shectory_dot_quik_dot_v1_dot_runner__bridge__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in shectory/quik/v1/runner_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RunnerBridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTicks = channel.unary_stream(
                '/shectory.quik.v1.RunnerBridge/StreamTicks',
                request_serializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.TickFilter.SerializeToString,
                response_deserializer=shectory_dot_quik_dot_v1_dot_quik__agent__pb2.MarketDataTick.FromString,
                _registered_method=True)
        self.StreamTape = channel.unary_stream(
                '/shectory.quik.v1.RunnerBridge/StreamTape',
                request_serializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.TickFilter.SerializeToString,
                response_deserializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.TapeBatch.FromString,
                _registered_method=True)
        self.PlaceRunnerOrder = channel.unary_unary(
                '/shectory.quik.v1.RunnerBridge/PlaceRunnerOrder',
                request_serializer=shectory_dot_quik_dot_v1_dot_quik__agent__pb2.PlaceOrder.SerializeToString,
                response_deserializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.BridgeAck.FromString,
                _registered_method=True)
        self.CancelRunnerOrder = channel.unary_unary(
                '/shectory.quik.v1.RunnerBridge/CancelRunnerOrder',
                request_serializer=shectory_dot_quik_dot_v1_dot_quik__agent__pb2.CancelOrder.SerializeToString,
                response_deserializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.BridgeAck.FromString,
                _registered_method=True)
        self.StreamOrderEvents = channel.unary_stream(
                '/shectory.quik.v1.RunnerBridge/StreamOrderEvents',
                request_serializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.EventsFilter.SerializeToString,
                response_deserializer=shectory_dot_quik_dot_v1_dot_quik__agent__pb2.OrderUpdate.FromString,
                _registered_method=True)
        self.StreamControl = channel.unary_stream(
                '/shectory.quik.v1.RunnerBridge/StreamControl',
                request_serializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.ControlHello.SerializeToString,
                response_deserializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.RunnerControl.FromString,
                _registered_method=True)
        self.ReportStatus = channel.unary_unary(
                '/shectory.quik.v1.RunnerBridge/ReportStatus',
                request_serializer=shectory_dot_quik_dot_v1_dot_quik__agent__pb2.RobotStatusReport.SerializeToString,
                response_deserializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.BridgeAck.FromString,
                _registered_method=True)


class RunnerBridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamTicks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTape(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceRunnerOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRunnerOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOrderEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunnerBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTicks': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTicks,
                    request_deserializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.TickFilter.FromString,
                    response_serializer=shectory_dot_quik_dot_v1_dot_quik__agent__pb2.MarketDataTick.SerializeToString,
            ),
            'StreamTape': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTape,
                    request_deserializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.TickFilter.FromString,
                    response_serializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.TapeBatch.SerializeToString,
            ),
            'PlaceRunnerOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceRunnerOrder,
                    request_deserializer=shectory_dot_quik_dot_v1_dot_quik__agent__pb2.PlaceOrder.FromString,
                    response_serializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.BridgeAck.SerializeToString,
            ),
            'CancelRunnerOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRunnerOrder,
                    request_deserializer=shectory_dot_quik_dot_v1_dot_quik__agent__pb2.CancelOrder.FromString,
                    response_serializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.BridgeAck.SerializeToString,
            ),
            'StreamOrderEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOrderEvents,
                    request_deserializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.EventsFilter.FromString,
                    response_serializer=shectory_dot_quik_dot_v1_dot_quik__agent__pb2.OrderUpdate.SerializeToString,
            ),
            'StreamControl': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamControl,
                    request_deserializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.ControlHello.FromString,
                    response_serializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.RunnerControl.SerializeToString,
            ),
            'ReportStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportStatus,
                    request_deserializer=shectory_dot_quik_dot_v1_dot_quik__agent__pb2.RobotStatusReport.FromString,
                    response_serializer=shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.BridgeAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shectory.quik.v1.RunnerBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shectory.quik.v1.RunnerBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RunnerBridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamTicks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shectory.quik.v1.RunnerBridge/StreamTicks',
            shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.TickFilter.SerializeToString,
            shectory_dot_quik_dot_v1_dot_quik__agent__pb2.MarketDataTick.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTape(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shectory.quik.v1.RunnerBridge/StreamTape',
            shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.TickFilter.SerializeToString,
            shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.TapeBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceRunnerOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shectory.quik.v1.RunnerBridge/PlaceRunnerOrder',
            shectory_dot_quik_dot_v1_dot_quik__agent__pb2.PlaceOrder.SerializeToString,
            shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.BridgeAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRunnerOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shectory.quik.v1.RunnerBridge/CancelRunnerOrder',
            shectory_dot_quik_dot_v1_dot_quik__agent__pb2.CancelOrder.SerializeToString,
            shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.BridgeAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamOrderEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shectory.quik.v1.RunnerBridge/StreamOrderEvents',
            shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.EventsFilter.SerializeToString,
            shectory_dot_quik_dot_v1_dot_quik__agent__pb2.OrderUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shectory.quik.v1.RunnerBridge/StreamControl',
            shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.ControlHello.SerializeToString,
            shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.RunnerControl.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shectory.quik.v1.RunnerBridge/ReportStatus',
            shectory_dot_quik_dot_v1_dot_quik__agent__pb2.RobotStatusReport.SerializeToString,
            shectory_dot_quik_dot_v1_dot_runner__bridge__pb2.BridgeAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
