from collections.abc import AsyncIterator, Awaitable, Callable
from typing import Protocol, runtime_checkable


@runtime_checkable
class MarketDataSource(Protocol):
    async def start(self, get_token: Callable[[bool], Awaitable[str]]) -> None: ...
    async def subscribe(self, symbol: str) -> None: ...
    def iter_quotes(self) -> AsyncIterator[dict]: ...
    async def close(self) -> None: ...
